### ISSUE TITLE
JetBrains - 2024 support

### ISSUE THREAD

**Issue by petrvecera** [profiq/docgen#17]
<img width="1119" alt="image" src="https://github.com/profiq/docgen/assets/8086995/d526d210-96cd-4b31-b84a-bc9eede052b0">

**Comment by msvana** [comment]
I probably have to contact the support. I am not specifying the "until" version and according to their docs "Undefined value declares compatibility with all the IDEs since the version specified by the since-build".

**Comment by petrvecera** [comment]
Ah, so it probably is faulty email then! I think we don't have to do anything :) Let's leave this comment until 2014 is in GA

**Comment by msvana** [comment]
I've discussed this with Jetbrains support, they guided me through some config changes. We should be fine after the new plugin version is approved:

![image](https://github.com/profiq/docgen/assets/4932888/402148bb-5557-458f-8a66-c426e0699f6c)

(241 should be equivalent to 2024.1)
