### ISSUE TITLE
Pycharm freezes on Ubuntu after installation

### ISSUE THREAD

**Issue by martasd** [profiq/docgen#8]
We've experienced that Pycharm freezes after the plugin's installation. This happens only on Ubuntu. On MacOS, there's no such issue. The problem has been reported here: https://youtrack.jetbrains.com/issue/PY-60240

**Comment by msvana** [comment]
Closing because:

1. I couldn't replicate the issue
2. JetBrains says the issue should be fixed by them in the next release
