### ISSUE TITLE
Waiting for OpenAI dialog hangs when insufficient_quota error occurs

### ISSUE THREAD

**Issue by martasd** [profiq/docgen#9]
Feedback od Šaňa:

Kolega pouzival (docgen v Pycharmu na Windows) a pri jeho free GPT verzi mu to vyhodilo tuto chybu pri generovani docstring, coz je asi ocakavane:

![image](https://user-images.githubusercontent.com/591911/234525636-2c79b49f-1c5c-41f7-98ee-8893444f61e3.png)

Problem je, ze pak ten window, ktory akoby caka na odpoved openAI sa zasekne a neda sa zavriet ani to Cancel tlacitko nereaguje. Pak je nutny restart PyCharmu.

**Comment by msvana** [comment]
Steps to replicate: 
1. Set your OpenAI API hard spending limit below your current monthly usage
2. Wait a few minutes
3. Try to use Docgen

EDIT: The same issue occurs with other errors, e.g., using a non-existing model
